#!/bin/bash
#adds all the relevant files to git
git add git_add_script README.txt
git add 2D_riblet/0 2D_riblet/system 2D_riblet/constant
git add 2D_riblet/run_script 2D_riblet/combine_script 2D_riblet/mpi_script_interFoam.sh
git add 2D_riblet/parameters.dat
